##Jupyter作業環境用
version: "3.9"

services:
  web:
    build: .
    ports:
      - '8880:8880'
    volumes:
      - '.:/workspace'
    command: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8880
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    restart: always
    tty: true
    stdin_open: true